
name: Auto Assign Reviewers and Assignees

on:
  pull_request:
    types: [opened]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign
        uses: kentaro-m/auto-assign-action@V2.0.0
        with:
          addReviewers: true
          addAssignees: author
          reviewers: |
            AyeNweTun
            StevenYu0124
            sweetpear0108
            aungtuntun-9823

          numberOfReviewers: 0
          numberOfAssignees: 3
        #  exclude:
        #    - sub-task
